#type 'make' to build files
all: test6 postfix delimiters

#type ./test6
test6: test6.cpp
	g++ -o test6 -std=c++11 test6.cpp

#type ./postfix
postfix: postfix.cpp
	g++ -o postfix -std=c++11 postfix.cpp

#type ./delimiters
delimiters: delimiters.cpp
	g++ -o delimiters -std=c++11 delimiters.cpp
